### ISSUE TITLE
I can't install angdist

### ISSUE THREAD

**Issue by kimdn** [Guillawme/angdist#1]
(base) [kimd999@glogin2 angdist]$ pip install angdist
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement angdist (from versions: none)
ERROR: No matching distribution found for angdist
WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
You should consider upgrading via the '/home/scicons/cascade/apps/eman2.3.1/bin/python -m pip install --upgrade pip' command.

**Comment by Guillawme** [comment]
Hello,

Thank you for your interest in `angdist`. 😃 

It looks like you are using Python 2.7. I made this tool with Python 3.9, and have not tested it with earlier versions of Python. You should follow the advice in this deprecation warning and use a version of Python 3, because since the end of support of Python 2 more and more programs will stop working with it. It looks like many Python programs are now based on Python 3.7, but which Python version you need depends largely on which Python programs you want to use.

It also looks like you are using conda, so I recommend creating a new environment with Python 3.9 and trying to install `angdist` in this new environment; it should work. Try running the following commands (replace `YOUR_ENV` with the name you want to give to this new conda environment). Get help from your system administrator if you are not sure how to do this.

```sh
conda deactivate # this will deactivate any conda environment you have currently active in your shell session
conda create --name YOUR_ENV python=3.9 # this will create a conda environment with a version of Python I know is compatible with angdist; you need to accept the installation when prompted
conda activate YOUR_ENV # this will set this new environment as the currently active one in your shell session
pip install angdist # this should now work
```

In general, it is a good idea to install complex Python programs (like EMAN2 that you are using) in a dedicated conda environment and not in your base environment, so their installation can also automatically install dependencies with compatible versions (when installing everything into the base environment, you are more likely to run into version conflicts between packages installed as dependencies). I made sure all these tools I made (this one, `angdist`, but also [`localres`](https://github.com/Guillawme/localres) and [`countparticles`](https://github.com/Guillawme/countparticles)) depend on the same versions of their dependencies, so you should be able to install them all in the same environment with no problem. But this is generally not the case when considering Python programs made by different authors.

I thought I had correctly declared the minimum Python version in this package (indeed, [the package's page on PyPI](https://pypi.org/project/angdist) indicates the correct Python version requirement), but I am not very familiar with Python, so it's possible that I missed something. I thought this should make `pip` report the incompatibility and suggest to use a compatible version of Python, instead of abruptly failing like that...

Let me know if you're able to `pip install angdist` successfully, and if so I will clarify the installation instructions in the README file to mention the details above.

**Comment by Guillawme** [comment]
Hello @kimdn 

Did you manage to install it?

**Comment by kimdn** [comment]
No, I moved on to another task, but I will come back if I need to see the Euler angle distribution visually. Thank you for making this nice program!

**Comment by Guillawme** [comment]
Ok, so I am closing this issue for now, as there is no evidence that the installation is broken in a fresh conda environment. But feel free to reopen if it doesn't work when you get around trying it.

**Comment by kimdn** [comment]
@Guillawme 

I successfully installed angdist and ran it. 

python=3.9 solved my issue as you mentioned.
